### ISSUE TITLE
What license is this script distributed under?

### ISSUE THREAD

**Issue by benklop** [sergesyrota/vmware-mysql-snapshot#4]
There is currently no information here about how you wish to license this script, and out of an abundance of caution, I can't really use it that way. Github's documentation suggests that without a license file, this project defaults to 'all rights reserved', and I'm not sure that is really your intention, especially given the source code comments suggesting that if any bugs are found or fixed, you'd welcome a PR.

Thanks!

**Comment by sergesyrota** [comment]
Updated with MIT license.
